### ISSUE TITLE
Setting any option fails with "FAILED: Error with password"

### ISSUE THREAD

**Issue by sdegeorgio** [tabacha/ProSafeLinux#28]
Hi,

Using the current ProSafeLinux master branch, I could not set any options on my GS108Ev3 switch.  Authentication always failed with the following string:
```
Changing Values..
using password hack on firmware: 20008
FAILED: Error with password
```
Digging into the code I found the problem was easily fixed: The incorrect variable “_password” is being used instead of “_plainpass” on line 363 of psl_class.py.  This meant an empty password was being used to authenticate with the switch instead of the password passed as a parameter on the command line.

Can someone update the repo?  Or provide me access so I can push the update?

Regards,
Stephan.

**Comment by tabacha** [comment]
Hi Stephan,
do you want to take over the project? 

If yes: its the best that you fork the project, and I will tell the folks to look at your repository.  There is also an other Pull request, which needs review.

If No: Plase provide a pull request.

**Comment by nmeid** [comment]
If Stephan is not interrested I might be, but I'm more thinking about a complete rewrite which I've already begun. 

I've been reverse engineering the protocol for a few days a couple of months ago, and I've made a "simulator" to make the process easier.

The project is far from complete, but the plan is to be able to configure everything which is possible in the ProSAFE Plus Utility.

https://github.com/nmedb/nsdpy

**Comment by sdegeorgio** [comment]
Hi Sven,

As much as I'd love to take on this project I don't have the time available.

I'm setting up a system to dynamically adjust VLAN settings on a test network of ~15 GS108Ev3 switches and from what I can see your software does everything I need which is really helpful!  If I find any other issues I'll let you know but I expect this issue was all that needed resolving.

Best regards,
Stephan de Georgio

**Comment by sdegeorgio** [comment]
Fixed in pull request.
